<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Master extends CI_Controller {

    function __construct() {
        parent::__construct();
        $this->load->model('Master_model');
        $this->load->library('form_validation');
        chek_session();
    }
	
	public function unitap() {    
        $this->template->display('master/tb_m_unitap_list');
    }
	
	public function unitup() {    
        $this->template->display('master/tb_m_unitup_list');
    }
	
	function view_m_unitap(){ 

        $no=1;               
        $transaksi_data = $this->Master_model->get_m_unitap();
            foreach ($transaksi_data as $transaksi) {
			$query[] = array(
                'no'=>$no++,
                'unitupi'=>$transaksi->unitupi,                
                'unitap'=>$transaksi->unitap,               
                'nama'=>$transaksi->nama,               
                'alamat'=>$transaksi->alamat,               
                'telp'=>$transaksi->telp              
            );
        }        
        $result=array('data'=>$query);
        echo  json_encode($result);
    }  
	
	function view_m_unitup(){ 
        $no=1;               
        $transaksi_data = $this->Master_model->get_m_unitup();
            foreach ($transaksi_data as $transaksi) {
			$query[] = array(
                'no'=>$no++,
                'unitap'=>$transaksi->unitap,
                'unitup'=>$transaksi->unitup,                
                'nama'=>$transaksi->nama,               
                'alamat'=>$transaksi->alamat,               
                'telp'=>$transaksi->telp                   
            );
        }        
        $result=array('data'=>$query);
        echo  json_encode($result);
    }  

}

/* End of file Transaksi.php */
/* Location: ./application/controllers/Transaksi.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-05-14 11:11:34 */
/* http://harviacode.com */