<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Dashboard_model extends CI_Model {

    function report(){
        $query = $this->db->query("select kd_vendor_pln,nama_vendor_pln,sum(rupiah2) rupiah from tb_tagihan_admedika_h
group by kd_vendor_pln,nama_vendor_pln 
order by rupiah desc limit 10");
         
        if($query->num_rows() > 0){
            foreach($query->result() as $data){
                $hasil[] = $data;
            }
            return $hasil;
        }
    }
}

/* End of file Transaksi_model.php */
/* Location: ./application/models/Transaksi_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-05-14 11:11:34 */
/* http://harviacode.com */