<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Master_model extends CI_Model {

    public $table = 'tb_transaksi';
    public $id = 'id_transaksi';
    public $order = 'DESC';

    function __construct() {
        parent::__construct();
    }
	
	function get_m_unitap() {
        return $this->db->query("SELECT * from tb_unitap")->result();
    }	
	
	function get_m_unitup() {
        return $this->db->query("SELECT * from tb_unitup")->result();
    }
	
}

/* End of file Transaksi_model.php */
/* Location: ./application/models/Transaksi_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-05-14 11:11:34 */
/* http://harviacode.com */